// Font settings
font_size 22.0

// Cursor settings
shell_integration no-cursor
cursor_shape block
cursor #ffdd33

// Overall settings
confirm_os_window_close 0
enable_audio_bell 0

// What shell kitty should use
shell fish

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family='Iosevka Fixed' postscript_name=Iosevka-Fixed
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
