#!/usr/bin/env bash
# Install this dotfiles repo onto a machine.
#
# Links the portable parts into place. Everything becomes a symlink, so the repo
# stays the single source of truth and edits in it take effect immediately.
# Nothing is overwritten silently: an existing file is renamed to a timestamped
# .bak first.
#
# Usage:
#   ./install.sh --dry-run    print what would happen, change nothing
#   ./install.sh --help       this text
#
# Platform differences are handled at runtime instead of in a separate macOS
# script: niri is Linux-only and is skipped on Darwin, and the notes at the end
# cover the font and the absolute paths baked into the Godot and Blender files.
# A second script would duplicate almost all of this and drift out of sync.

set -euo pipefail

REPO="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
OS="$(uname -s)"
DRY=0

for arg in "$@"; do
    case "$arg" in
        --dry-run|-n) DRY=1 ;;
        -h|--help)
            sed -n '3,17p' "$0" | sed 's/^#\{1,\} \{0,1\}//'
            exit 0
            ;;
        *) printf 'unknown option: %s\n' "$arg" >&2; exit 2 ;;
    esac
done

say()  { printf '  %s\n' "$*"; }
ok()   { printf '  ok    %s\n' "$*"; }
skip() { printf '  skip  %s\n' "$*"; }
warn() { printf '  WARN  %s\n' "$*" >&2; }
head1() { printf '\n%s\n' "$*"; }

# link <repo-relative-path> <label>
link() {
    rel="$1"
    label="$2"
    src="$REPO/$rel"
    dst="$CONFIG/$rel"

    if [ ! -e "$src" ]; then
        skip "$label (not in this repo)"
        return 0
    fi

    if [ -L "$dst" ]; then
        current="$(readlink "$dst")"
        if [ "$current" = "$src" ]; then
            ok "$label (already linked)"
            return 0
        fi
        warn "$label currently links to $current"
    elif [ -e "$dst" ]; then
        if [ "$DRY" -eq 1 ]; then
            warn "$label exists as a real file - would back it up and link it"
            return 0
        fi
        backup="$dst.bak-$(date +%Y%m%d%H%M%S)"
        mv "$dst" "$backup"
        say "$label: existing file saved as $(basename "$backup")"
    fi

    if [ "$DRY" -eq 1 ]; then
        say "$label -> $src  (dry run)"
        return 0
    fi

    mkdir -p "$(dirname "$dst")"
    ln -s "$src" "$dst"
    ok "$label -> $src"
}

printf 'Installing dotfiles from %s\n' "$REPO"
printf 'Platform: %s   Config root: %s%s\n' "$OS" "$CONFIG" \
    "$([ "$DRY" -eq 1 ] && printf '   [DRY RUN - nothing will be changed]')"

head1 'Neovim'
link nvim/init.lua        'init.lua'
link nvim/lua             'lua/ (plugins: godot_dev, keysearch)'
link nvim/README.md       'README.md'
link nvim/tags            'tags'
say 'nvim-pack-lock.json is written by Neovim itself; not linked'
say 'Plugins install automatically on first launch (vim.pack.add in init.lua)'

head1 'Terminal (kitty)'
link kitty/kitty.conf         'kitty.conf'
link kitty/current-theme.conf 'current-theme.conf'
skip 'kitty.conf.bak (old backup, intentionally untracked)'
if [ "$OS" = "Darwin" ]; then
    say 'On macOS also install the font kitty asks for, e.g.:'
    say '  brew install --cask font-iosevka   # then check: kitty +kitten list-fonts'
else
    say 'Font on Linux: install Iosevka, e.g. dnf install iosevka-fonts'
fi

head1 'Shell (fish)'
link fish/config.fish 'config.fish'
skip 'fish_variables (generated by fish itself)'
if [ "$OS" != "Darwin" ]; then
    say 'config.fish also holds aliases for Linux-only tools and hardware'
    say '(zapret, /dev/ttyUSB0 arduino, wine). They are harmless on macOS but'
    say 'will never resolve there.'
fi

head1 'Godot'
link godot/editor_settings-4.7.tres 'editor_settings-4.7.tres'
link godot/nvim-godot.sh          'nvim-godot.sh (external editor bridge)'
chmod_ok=0
if [ -f "$CONFIG/godot/nvim-godot.sh" ] && [ ! -x "$CONFIG/godot/nvim-godot.sh" ]; then
    chmod_ok=1
fi
if [ "$DRY" -eq 0 ] && [ "$chmod_ok" -eq 1 ]; then
    chmod +x "$CONFIG/godot/nvim-godot.sh"
    say 'nvim-godot.sh made executable'
fi
warn 'these absolute paths in editor_settings need editing for this machine:'
grep -n '/home/kirill' "$REPO/godot/editor_settings-4.7.tres" 2>/dev/null |
    sed 's/^/        /' >&2 || true
say 'Set the external editor in Godot: Editor Settings -> Text Editor -> External'

head1 'Blender'
for ver in 5.1 5.2; do
    [ -d "$REPO/blender/$ver" ] || continue
    for rel in config/startup.blend config/userpref.blend; do
        link "blender/$ver/$rel" "$ver/$rel"
    done
    skip "$ver/config/recent-files.txt, recent-searches.txt (machine state)"
done
warn 'bookmarks.txt holds /home/kirill paths - edit or delete on the new machine'

head1 'Wayland compositor (niri)'
if [ "$OS" = "Darwin" ]; then
    skip 'niri is Linux-only. macOS needs a different tiling WM, for example:'
    say '  AeroSpace   brew install --caskaerospace   (niri-style, closest)'
    say '  Amethyst    brew install --cask amethyst'
    say '  yabai + skhd  for a more X11/macOS-native feel'
    say 'The niri config cannot be reused; keybindings must be rewritten.'
else
    link niri/config.kdl 'config.kdl'
    warn 'config.kdl names your monitor (output "HDMI-A-4") and autostarts'
    warn 'noctalia-shell - both will differ on another machine.'
fi

head1 'Done'
if [ "$DRY" -eq 1 ]; then
    say 'This was a dry run. Re-run without --dry-run to apply.'
fi
say 'Restart Neovim and kitty. Plugins install on first Neovim launch.'
exit 0