-- Turn a documentation page into styled text for a normal Neovim buffer.
--
-- Not a browser. There is no layout engine here and none can be: a buffer is a
-- grid of cells, so floats, flexbox and web fonts are not reproducible. What
-- this does instead is keep the page's own structure and its own colours --
-- headings, lists, tables, links, code with the stylesheet's syntax colours --
-- and hand back lines plus highlight ranges so the result is an ordinary
-- buffer: searchable, yankable, jumpable.
--
-- The parser is a single pass over the article with an explicit state stack. It
-- is not a conforming HTML parser and does not need to be: the input is Sphinx
-- output, which is well-formed and generated by one tool.

local M = {}

--------------------------------------------------------------------------------
-- Entities
--------------------------------------------------------------------------------

local ENTITIES = {
    amp = '&', lt = '<', gt = '>', quot = '"', apos = "'", nbsp = ' ',
    mdash = '\226\128\148', ndash = '\226\128\147', hellip = '\226\128\166',
    laquo = '\194\171', raquo = '\194\187', lsquo = '\226\128\152',
    rsquo = '\226\128\153', ldquo = '\226\128\156', rdquo = '\226\128\157',
    times = '\194\151', rarr = '\226\134\146', larr = '\226\134\144',
    deg = '\194\176', plusmn = '\194\177', middot = '\194\183',
    copy = '\194\169', reg = '\194\174', trade = '\226\132\162',
    check = '\226\156\147', rsaquo = '\226\128\160', bull = '\226\128\162',
    lsaquo = '\226\128\158', ne = '\226\137\146', le = '\226\137\164',
    ge = '\226\137\163', rarrw = '\226\134\148', harr = '\226\134\152',
}

-- The glyphs Sphinx uses for a permalink icon: the link emoji, a pilcrow, and
-- the replacement character an invalid byte collapses into.
local PERMALINK = '\240\159\148\151\194\182\239\131\129'

local function decode(text)
    if not text:find('&', 1, true) then
        return text
    end
    return (text:gsub('&(#?)([%w]+);', function(kind, body)
        if kind == '#' then
            local code = tonumber(body)
            if not code or code < 32 or code > 0x10FFFF then
                return '&' .. kind .. body .. ';'
            end
            -- utf8 encoding of a code point
            return vim.fn.nr2char(code)
        end
        return ENTITIES[body] or ('&' .. body .. ';')
    end))
end

--------------------------------------------------------------------------------
-- Pygments token classes
--------------------------------------------------------------------------------

-- Sphinx highlights code with Pygments and ships the matching CSS. Mapping the
-- class names onto the stylesheet's own highlight colours is what makes a code
-- block look like the one on the site.
local function pygments_group(class)
    if class == '' then
        return nil
    end
    -- Longest names first: 'nf' must not be caught by the 'n' rule.
    if class:match('^k[cdnw]?$') or class == 'kp' or class == 'kr' then
        -- Control-flow keywords get their own colour in the stylesheet.
        if class == 'kc' or class == 'kd' or class == 'kn' then
            return 'GodotDocControl'
        end
        return 'GodotDocKeyword'
    end
    if class == 'kt' then return 'GodotDocBaseType' end
    if class:match('^kd$') then return 'GodotDocControl' end
    if class:match('^nf') or class:match('^fm') then return 'GodotDocFuncDecl' end
    if class:match('^nb') then return 'GodotDocBaseType' end
    if class:match('^no') then return 'GodotDocFunction' end
    if class:match('^nd') or class:match('^nc') or class:match('^nn')
        or class:match('^ne') or class:match('^nt') or class:match('^nv')
    then
        return 'GodotDocText'
    end
    if class == 'gd' then return 'GodotDocGlobalFunc' end
    if class == 'ge' then return 'GodotDocError' end
    if class:match('^s') then return 'GodotDocString' end
    if class:match('^c') then return 'GodotDocComment' end
    if class == 'mo' then return 'GodotDocOperator' end
    if class:match('^m') then return 'GodotDocNumber' end
    if class:match('^o') then return 'GodotDocOperator' end
    if class == 'p' then return 'GodotDocText' end
    if class == 'w' then return 'GodotDocCode' end
    if class == 'err' then return 'GodotDocError' end
    if class:match('^d') then return 'GodotDocDecorator' end
    return 'GodotDocCode'
end

--------------------------------------------------------------------------------
-- Parser
--------------------------------------------------------------------------------

local VOID = {
    br = true, hr = true, img = true, input = true, meta = true, link = true,
}

-- Tags whose text never reaches the page.
local SKIP = { script = true, style = true, noscript = true }

local function new_state()
    return {
        lines = {},
        cur = {},
        style = { bold = false, italic = false, code = false, link = false, pyg = nil },
        href = nil,
        link_mark = nil,
        heading = nil,
        indent = 0,
        lists = {},
        skip = 0,
        pre = nil,
        table = nil,
        cell = nil,
        pending_blank = false,
        -- id attribute -> output row. Every heading and member in the class
        -- reference carries one, so a reference to `#class-sprite2d-flip-h` can be
        -- resolved to a line instead of being ignored.
        anchors = {},
    }
end

local function flush(st)
    if st.cell then
        return false
    end
    -- Trailing spaces are dropped so a clipped cell does not pad its own line.
    local segs = st.cur
    while #segs > 0 and segs[#segs].t:match('^%s*$') do
        table.remove(segs)
    end
    if #segs == 0 then
        st.cur = {}
        return false
    end
    st.lines[#st.lines + 1] = segs
    st.cur = {}
    return true
end

local function blank(st)
    if st.cell then
        return
    end
    if #st.cur > 0 then
        flush(st)
    end
    if #st.lines > 0 and st.lines[#st.lines] ~= false then
        st.lines[#st.lines + 1] = false -- marker for an empty line
    end
end

local function resolve_inline(st)
    if st.heading then
        return 'GodotDocH' .. st.heading
    end
    if st.pre then
        return st.style.pyg or 'GodotDocCode'
    end
    local s = st.style
    if s.code then
        return s.bold and 'GodotDocLiteralBold' or 'GodotDocLiteral'
    end
    if s.link then
        return s.bold and 'GodotDocLinkBold' or 'GodotDocLink'
    end
    if s.bold and s.italic then return 'GodotDocBoldEm' end
    if s.bold then return 'GodotDocBold' end
    if s.italic then return 'GodotDocEm' end
    return 'GodotDocText'
end
local function push_text(st, text)
    if text == '' then
        return
    end
    -- Inside a table cell the text belongs to the cell, not to the line: a row is
    -- assembled from its cells afterwards and laid out as columns.
    local target = st.cell or st.cur
    -- Leading whitespace is layout in HTML, so a line never starts with one.
    if #target == 0 then
        text = text:gsub('^%s+', '')
        if text == '' then
            return
        end
    end
    local hl = resolve_inline(st)
    local href = (not st.pre and st.style.link) and st.href or nil
    local last = target[#target]
    if last and last.h == hl and last.href == href then
        last.t = last.t .. text
    else
        target[#target + 1] = { t = text, h = hl, href = href }
    end
end


-- gmatch, not string.match_all: this is LuaJIT, which has no match_all.
local function attrs_of(tag)
    local attrs = {}
    for k, v in tag:gmatch('([%w%-:]+)%s*=%s*"([^"]*)"') do
        attrs[k:lower()] = v
    end
    if not next(attrs) then
        for k, v in tag:gmatch("([%w%-:]+)%s*=%s*'([^']*)'") do
            attrs[k:lower()] = v
        end
    end
    return attrs
end

-- Whitespace in HTML is layout, so runs of it collapse; inside <pre> they are
-- content and are kept.
local function collapse(text)
    return (text:gsub('%s+', ' '))
end

local function trim_trailing_space(st)
    local last = st.cur[#st.cur]
    if last then
        last.t = (last.t:gsub('%s+$', ''))
    end
end

local function emit_table(st)
    local rows = st.table
    st.table = nil
    if not rows or #rows == 0 then
        return
    end
    local width = 0
    for _, row in ipairs(rows) do
        width = math.max(width, #row)
    end
    -- Column widths from the widest cell, so the columns line up as a table and
    -- not as a run of separated fragments.
    local widths = {}
    for _, row in ipairs(rows) do
        for i, cell in ipairs(row) do
            local w = 0
            for _, seg in ipairs(cell) do
                w = w + vim.fn.strdisplaywidth(seg.t)
            end
            widths[i] = math.max(widths[i] or 0, w)
        end
    end
    for _, row in ipairs(rows) do
        local segs = {}
        for i, cell in ipairs(row) do
            local pad = (widths[i] or 0) - (function()
                local w = 0
                for _, seg in ipairs(cell) do
                    w = w + vim.fn.strdisplaywidth(seg.t)
                end
                return w
            end)()
            for _, seg in ipairs(cell) do
                segs[#segs + 1] = { t = seg.t, h = seg.h, href = seg.href }
            end
            if i < #row then
                segs[#segs + 1] = { t = string.rep(' ', pad + 2), h = 'GodotDocText' }
            end
        end
        st.lines[#st.lines + 1] = segs
    end
end

local function handle_tag(st, tag)
    local closing = tag:sub(1, 1) == '/'
    -- '/' then '?' unescaped: `%?` is an escaped literal question mark, so
    -- writing `/%?` would have demanded a literal '/?' and matched no closing
    -- tag at all.
    local name = tag:match('^/?([%w%-]+)')
    if not name then
        return
    end
    name = name:lower()
    local attrs = closing and {} or attrs_of(tag)

    if SKIP[name] then
        st.skip = st.skip + (closing and -1 or 1)
        return
    end

    -- Inside a code block: collect raw text, keep Pygments classes.
    if st.pre then
        if name == 'pre' and closing then
            local pre = st.pre
            st.pre = nil
            st.style.pyg = nil
            blank(st)
            for _, line in ipairs(pre.lines) do
                st.lines[#st.lines + 1] = line
            end
            st.lines[#st.lines + 1] = false
        elseif name == 'span' and not closing then
            st.style.pyg = pygments_group(attrs.class or '') or st.style.pyg
        elseif name == 'span' and closing then
            st.style.pyg = nil
        elseif name == 'br' then
            pre.lines[#pre.lines + 1] = {}
            pre.pending_break = true
        end
        return
    end

    if st.table then
        if name == 'table' and closing then
            st.cell = nil
            emit_table(st)
            return
        end
        if name == 'tr' and not closing then
            st.table.row = {}
        elseif name == 'tr' and closing then
            if st.table.row and #st.table.row > 0 then
                st.table[#st.table + 1] = st.table.row
            end
            st.table.row = nil
        elseif (name == 'td' or name == 'th') then
            if not closing then
                st.cell = {}
                st.cell_head = name == 'th'
            else
                local cell = st.cell or {}
                -- Trim the cell's own trailing whitespace.
                while #cell > 0 and cell[#cell].t:match('^%s*$') do
                    table.remove(cell)
                end
                if st.cell_head then
                    for _, seg in ipairs(cell) do
                        seg.h = 'GodotDocBaseType'
                    end
                end
                if st.table.row then
                    st.table.row[#st.table.row + 1] = cell
                end
                st.cell = nil
            end
            return
        end
    end

    -- Where this element will land: the line it is about to start. Recorded
    -- before any of its text is emitted, so the row is the one the content ends
    -- up on.
    if not closing and attrs.id and attrs.id ~= '' and not st.pre and not st.cell then
        st.anchors[attrs.id] = #st.lines
    end

    -- A link that is only the heading permalink holds the same character the
    -- stylesheet shows, so its text is dropped rather than rendered.
    if name == 'a' and not closing and (attrs.class or ''):find('headerlink') then
        st.skip = st.skip + 1
        return
    end
    if st.skip > 0 then
        if name == 'a' and closing then
            st.skip = st.skip - 1
        end
        return
    end

    if name == 'pre' and not closing then
        flush(st)
        st.pre = { lines = { {} } }
        return
    end
    if name == 'table' and not closing then
        blank(st)
        st.table = {}
        return
    end

    -- Headings
    local level = name:match('^h([1-6])$')
    if level then
        if closing then
            trim_trailing_space(st)
            flush(st)
            blank(st)
            st.heading = nil
        else
            flush(st)
            blank(st)
            st.heading = tonumber(level)
        end
        return
    end

    -- Lists
    if name == 'ul' or name == 'ol' then
        if closing then
            table.remove(st.lists)
            st.indent = math.max(st.indent - 1, 0)
            if #st.lists == 0 then
                trim_trailing_space(st)
                flush(st)
                blank(st)
            end
        else
            st.lists[#st.lists + 1] = { ordered = name == 'ol', count = 0 }
            st.indent = st.indent + 1
        end
        return
    end
    if name == 'li' then
        if closing then
            trim_trailing_space(st)
            flush(st)
        else
            flush(st)
            local list = st.lists[#st.lists]
            local bullet
            if list and list.ordered then
                list.count = list.count + 1
                bullet = tostring(list.count) .. '. '
            else
                bullet = '\226\128\162 ' -- bullet
            end
            st.cur[#st.cur + 1] = { t = string.rep('  ', st.indent - 1) .. bullet, h = 'GodotDocBullet' }
        end
        return
    end

    -- Definition lists and quoted text
    if name == 'dt' or name == 'dd' or name == 'blockquote' then
        if not closing then
            flush(st)
            if name == 'dd' or name == 'blockquote' then
                st.indent = st.indent + 1
            end
        else
            trim_trailing_space(st)
            flush(st)
            if name == 'dd' or name == 'blockquote' then
                st.indent = math.max(st.indent - 1, 0)
            end
        end
        return
    end

    if name == 'p' or name == 'section' or name == 'div' or name == 'tr' then
        if closing then
            trim_trailing_space(st)
            if flush(st) and #st.lists == 0 then
                blank(st)
            end
        end
        return
    end

    if name == 'br' then
        flush(st)
        return
    end

    if name == 'hr' then
        blank(st)
        st.lines[#st.lines + 1] = { { t = string.rep('\226\128\148', 40), h = 'GodotDocRule' } }
        st.lines[#st.lines + 1] = false
        return
    end

    -- Inline styling
    if name == 'strong' or name == 'b' then
        if closing then
            st.style.bold = false
        else
            st.style.bold = true
        end
    elseif name == 'em' or name == 'i' or name == 'dfn' then
        if closing then
            st.style.italic = false
        else
            st.style.italic = true
        end
    elseif name == 'code' or name == 'tt' or name == 'kbd' or name == 'samp' then
        if closing then
            st.style.code = false
        else
            st.style.code = true
        end
    elseif name == 'a' then
        local target = st.cell or st.cur
        if closing then
            -- Sphinx hangs a small permalink icon on every heading and member
            -- signature. In a browser that is an icon; here it would be a stray
            -- glyph, so a link whose whole text is that glyph is dropped.
            local mark = st.link_mark
            st.style.link = false
            st.href = nil
            st.link_mark = nil
            if mark then
                local only = true
                for i = mark + 1, #target do
                    if not target[i].t:match('^[' .. PERMALINK .. '%s]*$') then
                        only = false
                        break
                    end
                end
                if only then
                    for i = #target, mark + 1, -1 do
                        table.remove(target, i)
                    end
                end
            end
        else
            st.style.link = true
            st.href = attrs.href
            st.link_mark = #target
        end
    end
end

--------------------------------------------------------------------------------
-- Entry point
--------------------------------------------------------------------------------

function M.render(html)
    local st = new_state()
    local pos = 1
    local len = #html

    while pos <= len do
        local lt = html:find('<', pos, true)
        if not lt then
            break
        end
        if lt > pos then
            local chunk = html:sub(pos, lt - 1)
            if st.skip == 0 then
                if st.pre then
                    local pre = st.pre
                    local decoded = decode(chunk)
                    -- Text between spans keeps the class of the span it follows.
                    local last = pre.lines[#pre.lines]
                    for piece in (decoded .. '\n'):gmatch('([^\n]*)\n') do
                        if piece ~= '' then
                            last[#last + 1] = { t = piece, h = st.style.pyg or 'GodotDocCode' }
                        end
                        pre.lines[#pre.lines + 1] = {}
                    end
                    table.remove(pre.lines)
                else
                    push_text(st, collapse(decode(chunk)))
                end
            end
        end
        local gt = html:find('>', lt, true)
        if not gt then
            break
        end
        handle_tag(st, html:sub(lt + 1, gt - 1))
        pos = gt + 1
    end

    flush(st)

    -- Flatten to plain lines plus highlight ranges, dropping the blank markers.
    local out_lines, out_marks, out_links = {}, {}, {}
    local out_anchors = st.anchors
    for _, segs in ipairs(st.lines) do
        if segs == false then
            out_lines[#out_lines + 1] = ''
        else
            local text, col = {}, 0
            local row = #out_lines
            for _, seg in ipairs(segs) do
                text[#text + 1] = seg.t
                if seg.h then
                    out_marks[#out_marks + 1] = {
                        row, col, col + #seg.t, seg.h,
                    }
                end
                if seg.href then
                    out_links[#out_links + 1] = { row, col, col + #seg.t, seg.href }
                end
                col = col + #seg.t
            end
            out_lines[#out_lines + 1] = table.concat(text)
        end
    end

    -- Trim leading and trailing blank lines. Dropping N lines at the front moves
    -- every mark and link after them up by N, so the shift has to be applied to
    -- all of them: adjusting only the ones on row 0 left every other range
    -- pointing N lines below the text it belonged to.
    local removed = 0
    while out_lines[1] == '' do
        table.remove(out_lines, 1)
        removed = removed + 1
    end
    if removed > 0 then
        local kept_marks, kept_links = {}, {}
        for _, m in ipairs(out_marks) do
            if m[1] >= removed then
                m[1] = m[1] - removed
                kept_marks[#kept_marks + 1] = m
            end
        end
        for _, l in ipairs(out_links) do
            if l[1] >= removed then
                l[1] = l[1] - removed
                kept_links[#kept_links + 1] = l
            end
        end
        out_marks, out_links = kept_marks, kept_links
        local kept_anchors = {}
        for id, row in pairs(out_anchors) do
            if row >= removed then
                kept_anchors[id] = row - removed
            end
        end
        out_anchors = kept_anchors
    end
    while out_lines[#out_lines] == '' do
        table.remove(out_lines)
    end

    return out_lines, out_marks, out_links, out_anchors
end

function M.extract_article(html)
    local at = html:find('<div role="main"', 1, true)
    if not at then
        return html
    end
    local open_end = html:find('>', at, true)
    if not open_end then
        return html
    end
    local pos, depth = open_end + 1, 1
    while depth > 0 do
        local s, e = html:find('</?div', pos)
        if not s then
            break
        end
        if html:sub(s, s + 1) == '</' then
            depth = depth - 1
        else
            depth = depth + 1
        end
        if depth == 0 then
            return html:sub(open_end + 1, s - 1)
        end
        pos = e + 1
    end
    return html:sub(open_end + 1)
end

return M
